### ISSUE TITLE
microcoap application

### ISSUE THREAD

**Issue by sarathsanthoss** [RIOT-OS/applications#22] opened 2016-03-04 08:26 UTC
hi all,
         when i running make for microcoap application getting the following error.if anybody knows share it will be useful for me.. thanks in advance......

------for native board-------
```
giri@giri:~/RIOT/examples/microcoap_server$ make all
Building application "microcoap_server" for "native" with MCU "native".

"make" -C /home/giri/RIOT/pkg/microcoap
"make" -C /home/giri/RIOT/pkg/microcoap/microcoap
main-posix.c: In function ‘main’:
main-posix.c:12:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
 int main(int argc, char **argv) 
              ^
main-posix.c:12:27: error: unused parameter ‘argv’ [-Werror=unused-parameter]
 int main(int argc, char **argv) 
                           ^
cc1: all warnings being treated as errors
make[2]: *** [main-posix.o] Error 1
make[1]: *** [all] Error 2
make: *** [/home/giri/RIOT/examples/microcoap_server/bin/native/microcoap.a] Error 2
```
-------for samr21 board------
```
giri@giri:~/RIOT/examples/microcoap_server$ make BOARD=samr21-xpro
"make" -C /home/giri/RIOT/pkg/microcoap
"make" -C /home/giri/RIOT/pkg/microcoap/microcoap
main-posix.c:1:24: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
                        ^
compilation terminated.
make[2]: *** [main-posix.o] Error 1
make[1]: *** [all] Error 2
make: *** [/home/giri/RIOT/examples/microcoap_server/bin/samr21-xpro/microcoap.a] Error 2
```

**Comment by gebart** [comment] 2016-03-04 11:45
I can't reproduce, it builds fine on my PC. Also, the error message you posted is from the microcoap_server example in the RIOT repository, not from the microcoap application in applications.

Do you have any local changes to your working copy?
Did you update to the latest master?
Did you try checking out a fresh copy from github?

**Comment by bsmelo** [comment] 2016-03-04 16:32
I once got errors like these and solved it by manually removing the `bin` directory inside the application directory.

**Comment by sarathsanthoss** [comment] 2016-03-07 07:41
It's worked thank you...

**Comment by gebart** [comment] 2016-03-07 07:46
Closed as it is now working.

**Closed by gebart** 2016-03-07 07:46 UTC

**Comment by sarathsanthoss** [comment] 2016-03-07 08:37
hi all,
   can anyone teach me how to start microcoap-server example.....

**Comment by sarathsanthoss** [comment] 2016-03-07 08:42
if i am running on native as per read me file i'm getting the following result..i dont know after what to do? i also installed copper plugin and radvd,when i'm trying to ping in firefox it showing network unreachable..
LOG:
giri@giri:~/RIOT/examples/microcoap_server$ make term
/home/giri/RIOT/examples/microcoap_server/bin/native/microcoap_server.elf tap0 
RIOT native interrupts/signals initialized.
LED_GREEN_OFF
LED_RED_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: UNKNOWN (builddir: /home/giri/RIOT))
RIOT microcoap example application
Configured network interfaces:
Iface  5   HWaddr: 76:50:44:76:11:44 
           MTU:1280  HL:64  RTR  RTR_ADV  
           Source address length: 6
           Link type: wired
           inet6 addr: ff02::1/128  scope: local [multicast]
           inet6 addr: fe80::7450:44ff:fe76:1144/64  scope: local
           inet6 addr: ff02::1:ff76:1144/128  scope: local [multicast]
           inet6 addr: ff02::2/128  scope: local [multicast]
           inet6 addr: fc00::7450:44ff:fe76:1144/64  scope: global
           
Waiting for incoming UDP packet...

**Comment by gebart** [comment] 2016-03-07 09:21
@sarathsanthoss If you ask the question on the mailing list (https://lists.riot-os.org/mailman/listinfo/users) you will have a greater chance of getting help with your setup. You can also try `#RIOT-OS` on IRC (Freenode)

If you don't want to use the mailing list and prefer to keep the discussion on Github you can open a new issue in http://github.com/RIOT-OS/RIOT/issues, though I recommend using the mailing list for setup and configuration issues like this. See also https://github.com/RIOT-OS/RIOT/wiki/Contributing-to-RIOT#community

This question is also not related to the application repository, since the microcoap-server example is found in http://github.com/RIOT-OS/RIOT so I will now lock this thread.
